Update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -22,10 +22,18 @@ jobs:
       - uses: subosito/flutter-action@v1
         with:
           channel: "stable"
-      - run: flutter pub get   
+      - run: flutter pub get
       - run: flutter analyze
       - run: flutter test --coverage
       - run: flutter test --machine > test-results.json
+      - name: Display test results
+        run: cat test-results.json
+      - name: Check if test-results.json exists
+        run: |
+          if [ ! -f test-results.json ]; then
+            echo "test-results.json not found!"
+            exit 1
+          fi
       - uses: dorny/test-reporter@v1.4.2
         with:
           name: test-results
@@ -33,4 +41,4 @@ jobs:
           reporter: flutter-json
       - uses: VeryGoodOpenSource/very_good_coverage@v1.1.1
         with:
-          min_coverage: 0     
+          min_coverage: 0
